// Shared constants
export const BRAND1 = "#c8aa6e";
export const BRAND2 = "#e7d6a8";

// Admin user data
export const ADMIN = {
  name: "AMRI AMIT",
  ic: "940120126733"
};

// Job positions for Add Staff
export const JOB_POSITIONS = [
  "PEGAWAI PERUBATAN",
  "PEGAWAI FARMASI",
  "PENOLONG PEGAWAI PERUBATAN",
  "JURURAWAT",
  "PENOLONG PEGAWAI FARMASI",
  "JURUTEKNOLOGI MAKMAL PERUBATAN",
  "JURUPULIH PERUBATAN CARAKERJA",
  "JURUPULIH FISIOTERAPI",
  "JURU-XRAY",
  "PENOLONG PEGAWAI TADBIR",
  "PEMBANTU KHIDMAT AM",
  "PEMBANTU PERAWATAN KESIHATAN",
  "PEMBANTU TADBIR",
  "JURURAWAT MASYARAKAT",
  "PENOLONG JURUTERA",
  "PEMBANTU PENYEDIAAN MAKANAN",
];
