import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
  },
  summaryHeader: {
    backgroundColor: 'rgba(0, 255, 200, 0.1)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.3)',
  },
  summaryText: {
    color: '#00ffc8',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  paginationInfo: {
    color: '#8a7f6a',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 4,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    color: '#e9ddc4',
    marginLeft: 12,
    fontSize: 16,
  },
  errorContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  errorText: {
    color: '#ff4757',
    fontSize: 16,
    textAlign: 'center',
    marginVertical: 12,
  },
  retryButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: 'rgba(0, 255, 200, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.4)',
  },
  retryButtonText: {
    color: '#00ffc8',
    fontSize: 14,
    fontWeight: '600',
  },
  warningContainer: {
    backgroundColor: 'rgba(255, 193, 7, 0.1)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 193, 7, 0.3)',
  },
  warningText: {
    color: '#ffc107',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingBottom: 20,
  },
  tableContainer: {
    minWidth: 1200, // Ensure table is wide enough (adjusted for name, IC, and jawatan columns)
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#1a1a2e',
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#3a3a5e',
  },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: '#0f0f1f',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2a4e',
    alignItems: 'center',
    minHeight: 50,
  },
  emptyRow: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyText: {
    color: '#8a7f6a',
    fontSize: 16,
    textAlign: 'center',
  },
  headerCell: {
    color: '#e9ddc4',
    fontWeight: 'bold',
    textAlign: 'center',
    paddingHorizontal: 4,
    fontSize: 12,
  },
  cell: {
    color: '#e9ddc4',
    textAlign: 'center',
    paddingHorizontal: 4,
    fontSize: 11,
  },
  cellText: {
    color: '#e9ddc4',
    textAlign: 'center',
    fontSize: 11,
  },
  cellNo: {
    width: 40,
  },
  cellDate: {
    width: 80,
  },
  cellName: {
    width: 180,
    textAlign: 'left',
    paddingLeft: 8,
  },
  cellIc: {
    width: 120,
    textAlign: 'center',
    fontSize: 10,
  },
  cellJawatan: {
    width: 150,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cellStatus: {
    width: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cellScore: {
    width: 80,
  },
  jawatanText: {
    fontSize: 9,
    textAlign: 'center',
    color: '#e9ddc4',
    lineHeight: 12,
  },
  statusButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    minWidth: 50,
    alignItems: 'center',
  },
  statusText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  remedialText: {
    fontSize: 10,
    fontWeight: 'bold',
  },
  // Modal Styles
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    padding: 20,
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: '#a8b8d8',
    alignSelf: 'center',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(100, 200, 255, 0.2)',
  },
  modalTitle: {
    color: '#a8b8d8',
    fontSize: 20,
    fontWeight: 'bold',
  },
  closeButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(168, 184, 216, 0.1)',
  },
  modalBody: {
    maxHeight: '80%',
  },
  detailSection: {
    marginBottom: 24,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 12,
    padding: 16,
  },
  detailSectionTitle: {
    color: '#e9ddc4',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  detailLabel: {
    color: '#8a7f6a',
    fontSize: 14,
    fontWeight: '600',
  },
  detailValue: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  scoreDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingVertical: 4,
  },
  scoreDetailLabel: {
    color: '#8a7f6a',
    fontSize: 14,
    fontWeight: '600',
  },
  scoreDetailValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#e9ddc4',
  },
  checklistDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(100, 200, 255, 0.1)',
  },
  checklistDetailProcedure: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: 'bold',
    flex: 1,
  },
  checklistDetailScore: {
    color: '#00ffc8',
    fontSize: 14,
    fontWeight: '600',
  },
  // Checklist Detail Modal Styles
  checklistStepItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    paddingHorizontal: 8,
  },
  checklistStepText: {
    color: '#e9ddc4',
    fontSize: 13,
    marginLeft: 8,
    flex: 1,
    lineHeight: 18,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
    paddingVertical: 2,
  },
  summaryLabel: {
    color: '#8a7f6a',
    fontSize: 14,
    fontWeight: '600',
  },
  summaryValue: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Checklist Section Styles
  checklistSection: {
    marginBottom: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(100, 200, 255, 0.1)',
  },
  checklistSectionTitle: {
    color: '#00ffc8',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 255, 200, 0.3)',
    paddingBottom: 6,
  },
  // Comments Styles
  commentsContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(100, 200, 255, 0.2)',
  },
  commentsText: {
    color: '#e9ddc4',
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'italic',
  },
  // Pretest Modal Styles
  clickableScore: {
    color: '#00ffc8',
    textDecorationLine: 'underline',
  },
  disabledScore: {
    color: '#8a7f6a',
  },
  cellScoreText: {
    color: '#e9ddc4',
    textAlign: 'center',
    paddingHorizontal: 4,
    fontSize: 11,
  },
  scoreButton: {
    padding: 4,
    borderRadius: 4,
  },
  // Question Container Styles
  questionContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(100, 200, 255, 0.2)',
  },
  questionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionNumber: {
    color: '#00ffc8',
    fontSize: 16,
    fontWeight: 'bold',
  },
  answerStatus: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
  },
  answerStatusText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  questionText: {
    color: '#e9ddc4',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  choicesContainer: {
    marginBottom: 12,
  },
  choiceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(100, 200, 255, 0.1)',
  },
  userAnswerChoice: {
    backgroundColor: 'rgba(255, 193, 7, 0.2)',
    borderColor: '#ffc107',
  },
  correctAnswerChoice: {
    backgroundColor: 'rgba(40, 167, 69, 0.2)',
    borderColor: '#28a745',
  },
  choiceLetter: {
    color: '#8a7f6a',
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 8,
    minWidth: 20,
  },
  choiceText: {
    color: '#e9ddc4',
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  userAnswerText: {
    color: '#ffc107',
    fontWeight: 'bold',
  },
  correctAnswerText: {
    color: '#28a745',
    fontWeight: 'bold',
  },
  choiceIcon: {
    marginLeft: 8,
  },
  answerSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(100, 200, 255, 0.1)',
  },
  answerSummaryText: {
    color: '#8a7f6a',
    fontSize: 12,
    fontWeight: '600',
  },
  // Tab Navigation Styles
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    marginBottom: 16,
    padding: 4,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: '#00ffc8',
  },
  tabText: {
    color: '#8a7f6a',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  activeTabText: {
    color: '#1a1a2e',
  },
  // Search and Filter Controls
  controlsContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    gap: 12,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: '#e9ddc4',
    fontSize: 14,
  },
  clearButton: {
    marginLeft: 8,
    padding: 4,
  },
  dateFilterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#00ffc8',
  },
  dateFilterText: {
    color: '#00ffc8',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 6,
    flex: 1,
  },
  dropdownIcon: {
    marginLeft: 8,
  },
  exportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#00ffc8',
  },
  exportButtonText: {
    color: '#00ffc8',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 6,
  },
  // Pagination Styles
  paginationControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(26, 26, 46, 0.8)',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(58, 58, 94, 0.5)',
  },
  resultsPerPageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  resultsPerPageLabel: {
    color: '#8a7f6a',
    fontSize: 11,
    fontWeight: '500',
    marginRight: 6,
  },
  resultsPerPageButtons: {
    flexDirection: 'row',
    gap: 2,
  },
  resultsPerPageButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(42, 42, 62, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(58, 58, 94, 0.3)',
    minWidth: 28,
    alignItems: 'center',
  },
  resultsPerPageButtonActive: {
    backgroundColor: '#00ffc8',
    borderColor: '#00ffc8',
  },
  resultsPerPageButtonText: {
    color: '#8a7f6a',
    fontSize: 10,
    fontWeight: '600',
  },
  resultsPerPageButtonTextActive: {
    color: '#1a1a2e',
  },
  pageNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pageButton: {
    padding: 6,
    borderRadius: 4,
    backgroundColor: 'rgba(42, 42, 62, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(58, 58, 94, 0.3)',
    minWidth: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageButtonDisabled: {
    backgroundColor: 'rgba(26, 26, 46, 0.3)',
    borderColor: 'rgba(42, 42, 62, 0.3)',
  },
  pageInfo: {
    color: '#8a7f6a',
    fontSize: 10,
    fontWeight: '600',
    minWidth: 40,
    textAlign: 'center',
  },
  // Statistics Styles
  statsContainer: {
    padding: 16,
  },
  statsHeader: {
    marginBottom: 24,
    alignItems: 'center',
  },
  statsTitle: {
    color: '#e9ddc4',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
  },
  statsSubtitle: {
    color: '#8a7f6a',
    fontSize: 14,
    textAlign: 'center',
  },
  emptyStatsContainer: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  emptyStatsText: {
    color: '#8a7f6a',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 16,
  },
  questionStatCard: {
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  questionStatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionStatNumber: {
    color: '#00ffc8',
    fontSize: 16,
    fontWeight: 'bold',
  },
  questionStatAccuracy: {
    alignItems: 'center',
  },
  accuracyText: {
    color: '#e9ddc4',
    fontSize: 18,
    fontWeight: 'bold',
  },
  accuracyLabel: {
    color: '#8a7f6a',
    fontSize: 12,
  },
  questionStatText: {
    color: '#e9ddc4',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  questionStatDetails: {
    marginBottom: 12,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  statLabel: {
    color: '#8a7f6a',
    fontSize: 12,
    fontWeight: '600',
  },
  statValue: {
    color: '#e9ddc4',
    fontSize: 12,
    fontWeight: 'bold',
  },
  accuracyBar: {
    height: 6,
    backgroundColor: '#3a3a5e',
    borderRadius: 3,
    overflow: 'hidden',
  },
  accuracyBarFill: {
    height: '100%',
    backgroundColor: '#00ffc8',
    borderRadius: 3,
  },
  // Date Filter Styles
  dateFilterContainer: {
    padding: 16,
  },
  filterTypeContainer: {
    marginBottom: 20,
  },
  filterTypeTitle: {
    color: '#e9ddc4',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  filterTypeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  filterTypeButtonActive: {
    backgroundColor: '#00ffc8',
    borderColor: '#00ffc8',
  },
  filterTypeText: {
    color: '#00ffc8',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 12,
  },
  filterTypeTextActive: {
    color: '#1a1a2e',
  },
  customDateContainer: {
    marginBottom: 20,
    alignItems: 'center',
  },
  customDateTitle: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  // Date Picker Styles
  datePickerContainer: {
    padding: 16,
    alignItems: 'center',
  },
  datePickerLabel: {
    color: '#e9ddc4',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  dateInput: {
    backgroundColor: '#0f0f1f',
    borderRadius: 8,
    padding: 12,
    color: '#e9ddc4',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#3a3a5e',
    marginBottom: 20,
  },
  datePickerButtons: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
    maxWidth: 280,
  },
  datePickerButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#3a3a5e',
    alignItems: 'center',
  },
  datePickerButtonPrimary: {
    backgroundColor: '#00ffc8',
  },
  datePickerButtonText: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: 'bold',
  },
  datePickerButtonTextPrimary: {
    color: '#1a1a2e',
  },
  // Calendar Styles
  calendarContainer: {
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    maxWidth: 280,
    alignSelf: 'center',
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  calendarNavButton: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(0, 255, 200, 0.1)',
  },
  calendarMonthYear: {
    color: '#e9ddc4',
    fontSize: 16,
    fontWeight: 'bold',
  },
  calendarDayNames: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  calendarDayName: {
    flex: 1,
    textAlign: 'center',
    color: '#8a7f6a',
    fontSize: 10,
    fontWeight: 'bold',
    paddingVertical: 4,
  },
  calendarDays: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarDay: {
    width: `${100/7}%`,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    margin: 1,
  },
  calendarDayEmpty: {
    width: `${100/7}%`,
    aspectRatio: 1,
    margin: 1,
  },
  calendarDaySelected: {
    backgroundColor: '#00ffc8',
  },
  calendarDayToday: {
    backgroundColor: 'rgba(0, 255, 200, 0.2)',
    borderWidth: 1,
    borderColor: '#00ffc8',
  },
  calendarDayText: {
    color: '#e9ddc4',
    fontSize: 12,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#1a1a2e',
    fontWeight: 'bold',
  },
  calendarDayTextToday: {
    color: '#00ffc8',
    fontWeight: 'bold',
  },
  // Dashboard Styles
  dashboardOverview: {
    flexDirection: 'row',
    marginBottom: 24,
    gap: 12,
  },
  overviewCard: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  overviewNumber: {
    color: '#e9ddc4',
    fontSize: 24,
    fontWeight: 'bold',
    marginVertical: 8,
  },
  overviewLabel: {
    color: '#8a7f6a',
    fontSize: 12,
    textAlign: 'center',
  },
  dashboardSection: {
    marginBottom: 20,
  },
  dashboardSectionTitle: {
    color: '#e9ddc4',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dashboardSectionSubtitle: {
    color: '#8a7f6a',
    fontSize: 14,
    marginBottom: 16,
  },
  dashboardQuestionCard: {
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  questionCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionNumberBadge: {
    backgroundColor: '#00ffc8',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  questionNumberText: {
    color: '#1a1a2e',
    fontSize: 12,
    fontWeight: 'bold',
  },
  questionAccuracyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  questionAccuracyText: {
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  questionCardText: {
    color: '#e9ddc4',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  questionCardStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 12,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statItemText: {
    color: '#8a7f6a',
    fontSize: 12,
    marginLeft: 4,
  },
  questionProgressContainer: {
    marginBottom: 8,
  },
  questionProgressBar: {
    height: 6,
    backgroundColor: '#3a3a5e',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 4,
  },
  questionProgressFill: {
    height: '100%',
    borderRadius: 3,
  },
  questionProgressText: {
    color: '#8a7f6a',
    fontSize: 10,
    textAlign: 'right',
  },
  wrongAnswerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 193, 7, 0.1)',
    borderRadius: 6,
    padding: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 193, 7, 0.3)',
  },
  wrongAnswerText: {
    color: '#8a7f6a',
    fontSize: 11,
    marginLeft: 6,
    flex: 1,
  },
  wrongAnswerValue: {
    color: '#ffc107',
    fontWeight: 'bold',
  },
  performanceChart: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#3a3a5e',
    height: 120,
  },
  chartBar: {
    alignItems: 'center',
    flex: 1,
  },
  chartBarContainer: {
    height: 80,
    width: 20,
    backgroundColor: '#3a3a5e',
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 8,
    justifyContent: 'flex-end',
  },
  chartBarFill: {
    width: '100%',
    borderRadius: 10,
  },
  chartBarLabel: {
    color: '#8a7f6a',
    fontSize: 10,
    fontWeight: 'bold',
  },
  chartBarValue: {
    color: '#e9ddc4',
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 2,
  },
  // Combined view styles
  combinedSection: {
    marginBottom: 20,
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  combinedSectionTitle: {
    color: '#00ffc8',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  testScoresContainer: {
    gap: 12,
  },
  testScoreItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#2a2a3e',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  testScoreLabel: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  testScoreValue: {
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 12,
  },
  checklistResultsContainer: {
    gap: 8,
  },
  checklistResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#2a2a3e',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  checklistResultInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  checklistResultLabel: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: '600',
    marginRight: 8,
  },
  checklistResultValue: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  viewDetailsButton: {
    backgroundColor: 'rgba(0, 255, 200, 0.2)',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.4)',
  },
  viewDetailsButtonText: {
    color: '#00ffc8',
    fontSize: 12,
    fontWeight: '600',
  },
  // Unified view styles
  testSection: {
    marginBottom: 20,
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  testHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#3a3a5e',
  },
  testTitle: {
    color: '#00ffc8',
    fontSize: 18,
    fontWeight: 'bold',
  },
  testScore: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: '600',
  },
  questionsContainer: {
    gap: 16,
  },
  questionCard: {
    backgroundColor: '#2a2a3e',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  questionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionNumber: {
    color: '#00ffc8',
    fontSize: 14,
    fontWeight: 'bold',
  },
  answerStatus: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  answerStatusText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  questionText: {
    color: '#e9ddc4',
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 12,
  },
  choicesContainer: {
    gap: 8,
  },
  choiceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#3a3a5e',
    backgroundColor: '#1a1a2e',
  },
  userAnswerChoice: {
    borderColor: '#ffc107',
    backgroundColor: 'rgba(255, 193, 7, 0.1)',
  },
  correctAnswerChoice: {
    borderColor: '#28a745',
    backgroundColor: 'rgba(40, 167, 69, 0.1)',
  },
  choiceLetter: {
    color: '#8a7f6a',
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 12,
    minWidth: 20,
  },
  choiceText: {
    color: '#e9ddc4',
    fontSize: 14,
    flex: 1,
  },
  userAnswerText: {
    color: '#ffc107',
    fontWeight: 'bold',
  },
  correctAnswerText: {
    color: '#28a745',
    fontWeight: 'bold',
  },
  checklistSection: {
    marginBottom: 20,
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  checklistHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#3a3a5e',
  },
  checklistTitle: {
    color: '#00ffc8',
    fontSize: 16,
    fontWeight: 'bold',
  },
  checklistStatus: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  checklistStatusText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  checklistInfo: {
    marginBottom: 12,
  },
  checklistScore: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  checklistComments: {
    color: '#8a7f6a',
    fontSize: 12,
    fontStyle: 'italic',
  },
  checklistSteps: {
    marginTop: 8,
  },
  statusContainer: {
    gap: 12,
  },
  statusItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2a2a3e',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  statusLabel: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: '600',
  },
  statusValue: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Simple combined view styles
  simpleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#2a2a3e',
    borderRadius: 6,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#3a3a5e',
  },
  simpleLabel: {
    color: '#e9ddc4',
    fontSize: 14,
    fontWeight: '600',
  },
  simpleValue: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Certificate Button Styles
  certificateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    minWidth: 60,
    gap: 4,
  },
  certificateButtonText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  // Crystal Mirror Dashboard Styles
  dashboardContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  modernHeader: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    marginBottom: 24,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(147, 197, 253, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modernTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: -0.5,
    textShadowColor: 'rgba(147, 197, 253, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  modernSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '400',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: 'rgba(147, 197, 253, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
    textShadowColor: 'rgba(147, 197, 253, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  emptyDescription: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    lineHeight: 20,
  },
  modernContent: {
    paddingHorizontal: 20,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 32,
  },
  metricCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.2)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 12,
  },
  metricIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(147, 197, 253, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  metricValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
    textShadowColor: 'rgba(147, 197, 253, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  metricLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
    marginBottom: 8,
  },
  metricTrend: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  trendText: {
    fontSize: 12,
    color: '#34D399',
    fontWeight: '600',
    textShadowColor: 'rgba(52, 211, 153, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  primaryCard: {
    backgroundColor: 'rgba(147, 197, 253, 0.1)',
    borderColor: 'rgba(147, 197, 253, 0.3)',
    shadowColor: '#93C5FD',
  },
  secondaryCard: {
    backgroundColor: 'rgba(251, 191, 36, 0.1)',
    borderColor: 'rgba(251, 191, 36, 0.3)',
    shadowColor: '#FBBF24',
  },
  successCard: {
    backgroundColor: 'rgba(52, 211, 153, 0.1)',
    borderColor: 'rgba(52, 211, 153, 0.3)',
    shadowColor: '#34D399',
  },
  warningCard: {
    backgroundColor: 'rgba(96, 165, 250, 0.1)',
    borderColor: 'rgba(96, 165, 250, 0.3)',
    shadowColor: '#60A5FA',
  },
  overviewSection: {
    marginBottom: 32,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(147, 197, 253, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  sectionActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  actionButtonText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '500',
  },
  overviewCards: {
    flexDirection: 'row',
    gap: 16,
  },
  overviewCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.2)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 12,
  },
  overviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  overviewTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(147, 197, 253, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  statusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    shadowColor: '#34D399',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
    elevation: 4,
  },
  statusText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
  },
  overviewStats: {
    gap: 12,
  },
  overviewStat: {
    gap: 4,
  },
  overviewValue: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '500',
  },
  overviewNumber: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
    textShadowColor: 'rgba(147, 197, 253, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  overviewSubtext: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.5)',
  },
  certificationStats: {
    gap: 12,
  },
  certificationItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  certificationLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '500',
  },
  certificationValue: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
    textShadowColor: 'rgba(147, 197, 253, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  // Professional Charts Section
  chartsSection: {
    marginBottom: 32,
  },
  chartsRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 20,
  },
  chartContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.2)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 12,
    marginBottom: 20,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(147, 197, 253, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  chartActions: {
    flexDirection: 'row',
    gap: 8,
  },
  chartActionButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
  },
  
  // Donut Chart Styles
  donutChartContainer: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.2)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 12,
  },
  donutChartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  donutChartTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(147, 197, 253, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  donutChartActions: {
    flexDirection: 'row',
    gap: 4,
  },
  donutChartWrapper: {
    alignItems: 'center',
    marginBottom: 16,
  },
  donutChart: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderWidth: 2,
    borderColor: 'rgba(147, 197, 253, 0.3)',
  },
  donutChartInner: {
    alignItems: 'center',
    zIndex: 2,
  },
  donutChartPercentage: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(147, 197, 253, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  donutChartLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
  },
  donutChartRing: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 8,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  donutChartSegment: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 8,
    borderColor: 'transparent',
    borderTopColor: 'currentColor',
    transformOrigin: 'center',
  },
  donutChartStats: {
    gap: 8,
  },
  donutStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  donutStatDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  donutStatText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
  },
  
  // Area Chart Styles
  areaChartContainer: {
    height: 200,
    flexDirection: 'row',
  },
  areaChartYAxis: {
    width: 40,
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  areaChartYLabel: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.5)',
    fontWeight: '500',
    textAlign: 'right',
  },
  areaChartContent: {
    flex: 1,
    position: 'relative',
  },
  areaChartGrid: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  areaChartGridLine: {
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  areaChartArea: {
    flex: 1,
    position: 'relative',
    marginTop: 10,
    marginBottom: 30,
  },
  areaChartPath: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  areaChartFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(147, 197, 253, 0.2)',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  areaChartLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 2,
    borderTopColor: '#93C5FD',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  areaChartDots: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  areaChartDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#93C5FD',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 8,
  },
  areaChartXAxis: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 10,
  },
  areaChartXLabel: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
    textAlign: 'center',
  },
  
  // Gauge Chart Styles
  gaugeChartContainer: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.2)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 12,
  },
  gaugeChartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  gaugeChartTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(147, 197, 253, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  gaugeChartWrapper: {
    alignItems: 'center',
    marginBottom: 16,
  },
  gaugeChart: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderWidth: 2,
    borderColor: 'rgba(147, 197, 253, 0.3)',
  },
  gaugeChartArc: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 6,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
  },
  gaugeChartFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 6,
    borderColor: 'transparent',
    borderTopColor: 'currentColor',
    transformOrigin: 'center',
  },
  gaugeChartCenter: {
    alignItems: 'center',
    zIndex: 2,
  },
  gaugeChartValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(147, 197, 253, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  gaugeChartLabel: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
  },
  gaugeChartLegend: {
    gap: 6,
  },
  gaugeLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  gaugeLegendDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  gaugeLegendText: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
  },
  
  // Clickable Card Styles
  clickableCard: {
    position: 'relative',
  },
  clickIndicator: {
    position: 'absolute',
    top: 12,
    right: 12,
    opacity: 0.7,
  },
  
  // Participant Modal Styles
  participantModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  participantModalContent: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: '#1a1a2e',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 16,
  },
  participantModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(147, 197, 253, 0.2)',
  },
  participantModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(147, 197, 253, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  participantModalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
  },
  participantModalBody: {
    maxHeight: '70%',
  },
  participantEmptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  participantEmptyText: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 12,
  },
  participantItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 16,
    margin: 8,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.2)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  participantItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  participantItemInfo: {
    flex: 1,
  },
  participantItemName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
    textShadowColor: 'rgba(147, 197, 253, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  participantItemId: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  participantItemStats: {
    alignItems: 'flex-end',
    gap: 4,
  },
  participantStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  participantStatLabel: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '500',
  },
  participantStatValue: {
    fontSize: 12,
    fontWeight: '600',
    minWidth: 30,
    textAlign: 'right',
  },
  participantItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  participantItemDate: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.6)',
  },
  participantItemStatus: {
    flexDirection: 'row',
    gap: 8,
  },
  participantStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
  },
  participantStatusText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontWeight: '500',
  },

  // Futuristic Dashboard Styles
  futuristicDashboardContainer: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  futuristicHeader: {
    position: 'relative',
    padding: 20,
    backgroundColor: 'rgba(0, 255, 200, 0.05)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 255, 200, 0.2)',
  },
  headerGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#00ffc8',
    shadowColor: '#00ffc8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
  },
  futuristicTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#00ffc8',
    textShadowColor: 'rgba(0, 255, 200, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  futuristicSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 5,
  },
  futuristicButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 255, 200, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.3)',
  },
  futuristicContent: {
    padding: 20,
  },

  // Highest Scores Section
  highestScoresSection: {
    marginBottom: 30,
  },
  futuristicSectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#00ffc8',
    marginBottom: 15,
    textShadowColor: 'rgba(0, 255, 200, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  sectionGlow: {
    position: 'absolute',
    bottom: -5,
    left: 0,
    width: 50,
    height: 2,
    backgroundColor: '#00ffc8',
    shadowColor: '#00ffc8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
  },
  scoresGrid: {
    flexDirection: 'row',
    gap: 15,
  },
  scoreCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 15,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  scoreCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 10,
  },
  scoreCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  scoreValues: {
    gap: 10,
  },
  scoreItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  scoreLabel: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  scoreValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00ffc8',
  },

  // Pass/Fail Section
  passFailSection: {
    marginBottom: 30,
  },
  chartsGrid: {
    flexDirection: 'row',
    gap: 15,
  },
  modernChartCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 15,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  chartBadge: {
    backgroundColor: 'rgba(0, 255, 200, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  chartBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#00ffc8',
  },
  donutChartContainer: {
    alignItems: 'center',
    marginBottom: 15,
  },
  donutChart: {
    width: 120,
    height: 120,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutChartInner: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  donutPercentage: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  donutLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  donutRing: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 8,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  donutSegment: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 8,
    borderColor: 'transparent',
    borderTopColor: '#00ffc8',
    transformOrigin: 'center',
  },
  chartLegend: {
    gap: 8,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
  },

  // Question Analysis Section
  questionAnalysisSection: {
    marginBottom: 30,
  },
  questionsList: {
    gap: 15,
  },
  questionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 15,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  questionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  questionNumber: {
    backgroundColor: 'rgba(0, 255, 200, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  questionNumberText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#00ffc8',
  },
  questionAccuracy: {
    alignItems: 'center',
  },
  accuracyText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ff6b6b',
  },
  accuracyLabel: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  questionText: {
    fontSize: 14,
    color: '#FFFFFF',
    lineHeight: 20,
    marginBottom: 15,
  },
  questionStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  statItem: {
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  suggestionBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 217, 61, 0.1)',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 217, 61, 0.3)',
    gap: 8,
  },
  suggestionText: {
    fontSize: 12,
    color: '#ffd93d',
    flex: 1,
    lineHeight: 16,
  },

  // Futuristic Stats Container Styles
  futuristicStatsContainer: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  futuristicStatsHeader: {
    position: 'relative',
    padding: 20,
    backgroundColor: 'rgba(0, 255, 200, 0.05)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 255, 200, 0.2)',
  },
  statsHeaderGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#00ffc8',
    shadowColor: '#00ffc8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
  },
  statsHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statsLogoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  futuristicStatsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#00ffc8',
    textShadowColor: 'rgba(0, 255, 200, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  futuristicStatsSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 5,
  },
  futuristicStatsContent: {
    padding: 20,
  },

  // Clickable score card styles
  clickHint: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.6)',
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },

  // Answer choices styles
  answerChoicesContainer: {
    marginVertical: 15,
    padding: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.1)',
  },
  answerChoicesTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#00ffc8',
    marginBottom: 10,
  },
  answerChoicesList: {
    gap: 12,
  },
  answerChoiceRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  answerChoiceBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  answerChoiceLetter: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  answerChoiceContent: {
    flex: 1,
  },
  answerChoiceText: {
    fontSize: 13,
    color: '#FFFFFF',
    lineHeight: 18,
    marginBottom: 4,
  },
  answerChoiceStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  answerChoiceCount: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  answerChoiceLabel: {
    fontSize: 11,
    fontWeight: 'bold',
  },

  // Date filter modal styles
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1a1a1a',
    borderRadius: 15,
    padding: 20,
    width: '90%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.3)',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 255, 200, 0.2)',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  modalCloseButton: {
    padding: 5,
  },
  dateFilterOptions: {
    gap: 12,
  },
  dateFilterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.2)',
  },
  dateFilterOptionActive: {
    backgroundColor: 'rgba(0, 255, 200, 0.1)',
    borderColor: '#00ffc8',
  },
  dateFilterOptionText: {
    fontSize: 16,
    color: '#FFFFFF',
    marginLeft: 12,
    fontWeight: '500',
  },

  // Highest Scorers Modal Styles
  highestScoreText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00ffc8',
    textAlign: 'center',
    marginBottom: 20,
  },
  scorersList: {
    gap: 12,
  },
  scorerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.2)',
  },
  scorerRank: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#00ffc8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  scorerRankText: {
    color: '#1a1a1a',
    fontSize: 16,
    fontWeight: 'bold',
  },
  scorerDetails: {
    flex: 1,
  },
  scorerName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  scorerPosition: {
    fontSize: 14,
    color: '#8a7f6a',
    marginBottom: 2,
  },
  scorerDate: {
    fontSize: 12,
    color: '#8a7f6a',
  },
  scorerScore: {
    backgroundColor: 'rgba(0, 255, 200, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#00ffc8',
  },
  scorerScoreText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#00ffc8',
  },
  modalFooter: {
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 255, 200, 0.2)',
  },
  modalButton: {
    backgroundColor: '#00ffc8',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#1a1a1a',
    fontSize: 16,
    fontWeight: 'bold',
  },
  closeButton: {
    padding: 5,
  },

  // Top 3 Ranking Styles
  firstPlace: {
    borderColor: '#FFD700',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderWidth: 2,
  },
  secondPlace: {
    borderColor: '#C0C0C0',
    backgroundColor: 'rgba(192, 192, 192, 0.1)',
    borderWidth: 2,
  },
  thirdPlace: {
    borderColor: '#CD7F32',
    backgroundColor: 'rgba(205, 127, 50, 0.1)',
    borderWidth: 2,
  },
  firstPlaceRank: {
    backgroundColor: '#FFD700',
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  secondPlaceRank: {
    backgroundColor: '#C0C0C0',
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  thirdPlaceRank: {
    backgroundColor: '#CD7F32',
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  firstPlaceRankText: {
    color: '#1a1a1a',
    fontSize: 20,
  },
  secondPlaceRankText: {
    color: '#1a1a1a',
    fontSize: 18,
  },
  thirdPlaceRankText: {
    color: '#1a1a1a',
    fontSize: 16,
  },
  firstPlaceName: {
    color: '#FFD700',
    fontSize: 18,
    fontWeight: 'bold',
  },
  firstPlaceScore: {
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    borderColor: '#FFD700',
  },
  secondPlaceScore: {
    backgroundColor: 'rgba(192, 192, 192, 0.2)',
    borderColor: '#C0C0C0',
  },
  thirdPlaceScore: {
    backgroundColor: 'rgba(205, 127, 50, 0.2)',
    borderColor: '#CD7F32',
  },
  firstPlaceScoreText: {
    color: '#FFD700',
    fontSize: 18,
    fontWeight: 'bold',
  },
  secondPlaceScoreText: {
    color: '#C0C0C0',
    fontSize: 16,
    fontWeight: 'bold',
  },
  thirdPlaceScoreText: {
    color: '#CD7F32',
    fontSize: 16,
    fontWeight: 'bold',
  },

  // Enhanced Dashboard Statistics Styles
  testStatsContainer: {
    marginBottom: 20,
  },
  testTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
    textAlign: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.2)',
    shadowColor: '#93C5FD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  passCard: {
    borderColor: 'rgba(16, 185, 129, 0.3)',
    backgroundColor: 'rgba(16, 185, 129, 0.05)',
  },
  failCard: {
    borderColor: 'rgba(239, 68, 68, 0.3)',
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
  },
  statHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 6,
  },
  statLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '500',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 4,
  },
  statPercentage: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
  },

  // Date Filter Status Styles
  dateFilterStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 255, 200, 0.1)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 200, 0.2)',
    gap: 8,
  },
  dateFilterStatusText: {
    fontSize: 14,
    color: '#00ffc8',
    fontWeight: '500',
    flex: 1,
  },

  // No Data Styles
  noDataContainer: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  noDataTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 16,
    marginBottom: 8,
  },
  noDataDescription: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    lineHeight: 20,
  },

  // Highest Scorers Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: '#333',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#f5ead1',
    flex: 1,
  },
  closeButton: {
    padding: 5,
    marginLeft: 10,
  },
  closeButtonText: {
    fontSize: 20,
    color: '#d7ccb7',
    fontWeight: 'bold',
  },
  modalBody: {
    maxHeight: 400,
  },
  scorerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    marginBottom: 10,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
  },
  rankContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#4a4a4a',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  rankText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#f5ead1',
  },
  scorerInfo: {
    flex: 1,
  },
  scorerName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#f5ead1',
    marginBottom: 4,
  },
  scorerScore: {
    fontSize: 14,
    color: '#d7ccb7',
    marginBottom: 2,
  },
  scorerCategory: {
    fontSize: 12,
    color: '#999',
    textTransform: 'capitalize',
  },
  noDataContainer: {
    padding: 20,
    alignItems: 'center',
  },
  noDataText: {
    fontSize: 16,
    color: '#d7ccb7',
    textAlign: 'center',
  },
});

export { styles };